AWSTemplateFormatVersion: '2010-09-09'
Description: A hello world application.
Globals:
  Function:
    Runtime: python3.6
    Timeout: 60
Resources:
  HelloWorldFunction:
    Properties:
      AutoPublishAlias: helloworld
      CodeUri: s3://serverless.akirakoyasu/sam-study/6f19014af3e8786572361b2560918675
      Handler: index.handler
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
