AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.

Globals:
  Function:
    Timeout: 60

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: helloworld
      Runtime: python3.6
      CodeUri: ./src/app
      Handler: index.handler
      Role: arn:aws:iam::638218825207:role/LambdaInvoke

  ParamsFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: params
      Runtime: python3.6
      CodeUri: ./src/app
      Handler: params.handler
      Role: arn:aws:iam::638218825207:role/LambdaInvoke
