#!/bin/bash
set -eu

cwd=$(cd $(dirname "$0"); pwd)
cd "${cwd}/.."

if [ $# -ge 1 -a "${1}" == "--" ]; then
  shift
  set -x
  exec docker-compose run --rm sam-local "$@"
else
  set -x
  exec docker-compose run --rm sam-local sam "$@"
fi
